### ISSUE TITLE
Newly added text that requires translation

### ISSUE THREAD

**Issue by ppelayo1** [codeforsanjose/project-happening-atm#222]
**This issue is created for storing newly added text that requires translation. Please add word/phrases below by editing this section or by adding a new comment.**

New keys were added to en/translation.yarn lines 280-294 and need to be translated for es and vi.

```login:
  header:
    cityLogo: City Logo
  body:
    header:
      welcomeToCity: Welcome to the City of San José
      cityCouncil: City Council Meeting Virtual Agenda
    oauth:
      google: Sign In with Google
      microsoft: Sign In with Microsoft
    or: or
    textSignIn:
      userName: Username
      password: Password
      forgotPass: Forgot Password?
```

```
meeting:
  tabs:
    agenda:
      list:
        subscribe:
          page:
            inputs:
              sms:
                us-support-note: We support only US phone numbers (ex. +1 (234) 567-8910)
```
